import { useRef, useState, useEffect } from "react";
import { usePageTitle } from "@/hooks/use-page-title";
import { motion, useInView, useScroll, useSpring } from "framer-motion";

function Reveal({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <motion.div ref={ref} className={className} initial={{ opacity: 0, y: 20 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.55, delay, ease: [0.16, 1, 0.3, 1] }}>
      {children}
    </motion.div>
  );
}

const sections = [
  { id: "acceptance", title: "1. Acceptance of Terms", content: `By accessing or using the Directioner bot ("Service"), website, or any associated APIs, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.\n\nThese Terms apply to all users, including Discord server administrators, end users, and developers who interact with the Service in any capacity. We reserve the right to modify these Terms at any time; continued use of the Service after changes constitutes acceptance.` },
  { id: "service-description", title: "2. Service Description", content: `Directioner is an AI-powered Discord bot that provides conversational AI, personality modes, voice responses, server memory, and analytics features. The Service is provided "as is" and is subject to availability.\n\nWe may, without notice, modify, suspend, or discontinue any aspect of the Service, including features, pricing, and availability. We are not liable for any modification, suspension, or discontinuation of the Service.` },
  { id: "eligibility", title: "3. Eligibility & Account Requirements", content: `You must be at least 13 years of age (or the age of digital consent in your jurisdiction, whichever is greater) to use the Service. By using the Service, you represent that you meet this requirement.\n\nYou are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account.` },
  { id: "usage-rules", title: "4. Acceptable Use", content: `You agree not to use the Service to: (a) violate any applicable law or regulation; (b) infringe on the intellectual property rights of others; (c) generate, distribute, or facilitate spam, phishing, or harmful content; (d) harass, abuse, or harm any person; (e) attempt to gain unauthorized access to any part of the Service or its infrastructure; (f) use the Service to generate content that is illegal, defamatory, obscene, or otherwise objectionable.\n\nWe reserve the right to suspend or terminate your access for violation of these rules without prior notice.` },
  { id: "ai-content", title: "5. AI-Generated Content", content: `The Service uses artificial intelligence to generate responses. AI-generated content may be inaccurate, incomplete, or inappropriate for certain contexts. You acknowledge that:\n\n(a) AI responses are not professional advice of any kind (legal, medical, financial, etc.);\n(b) You are solely responsible for how you interpret and act on AI-generated content;\n(c) We make no warranties regarding the accuracy, reliability, or completeness of AI outputs;\n(d) Content generated by the bot may reflect biases inherent in underlying AI models.\n\nYou should not rely on AI-generated content for critical decisions without independent verification.` },
  { id: "data", title: "6. Data & Privacy", content: `Our collection and use of personal data is governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the data practices described in the Privacy Policy.\n\nYou grant us a non-exclusive, worldwide, royalty-free license to use, store, process, and display the content you submit to the Service solely to operate and improve the Service. We do not sell your personal data to third parties.` },
  { id: "subscription", title: "7. Subscription & Billing", content: `Certain features of the Service require a paid subscription. Subscription fees are charged in advance and are non-refundable except where required by applicable law. You authorize us to charge your payment method for all fees incurred.\n\nSubscriptions auto-renew unless cancelled before the renewal date. You can cancel at any time through your account settings. Cancellation takes effect at the end of the current billing period; you will retain access to paid features until then.` },
  { id: "intellectual-property", title: "8. Intellectual Property", content: `The Service, including all software, design, trademarks, and content created by Directioner, is owned by Directioner and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our express written permission.\n\nYou retain ownership of content you submit to the Service. By submitting content, you grant us the limited license described in Section 6.` },
  { id: "disclaimers", title: "9. Disclaimers", content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.\n\nWe do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components. You use the Service at your own risk.` },
  { id: "limitation", title: "10. Limitation of Liability", content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, DIRECTIONER AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, DATA, OR GOODWILL.\n\nOUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THE USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.` },
  { id: "termination", title: "11. Termination", content: `We may terminate or suspend your access to the Service immediately, without prior notice, for any reason, including breach of these Terms. Upon termination, your right to use the Service ceases immediately.\n\nYou may terminate your account at any time by removing the bot from your Discord server and contacting us to delete your data. Sections 8, 9, and 10 survive termination.` },
  { id: "governing-law", title: "12. Governing Law & Disputes", content: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law provisions. Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules, except that either party may seek injunctive relief in a court of competent jurisdiction.\n\nYou waive any right to participate in a class action lawsuit or class-wide arbitration.` },
  { id: "contact", title: "13. Contact", content: `For questions about these Terms, please contact us at legal@directioner.app or through our contact page. We will respond to all legitimate inquiries within 5 business days.` },
];

export default function Terms() {
  usePageTitle("Terms of Service — Directioner");
  const [activeSection, setActiveSection] = useState("acceptance");
  const contentRef = useRef<HTMLDivElement>(null);

  /* Reading progress bar */
  const { scrollYProgress } = useScroll({ target: contentRef, offset: ["start start", "end end"] });
  const scaleX = useSpring(scrollYProgress, { stiffness: 100, damping: 30, restDelta: 0.001 });

  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) setActiveSection(e.target.id); }),
      { rootMargin: "-30% 0px -60% 0px" }
    );
    sections.forEach(({ id }) => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => observer.disconnect();
  }, []);

  return (
    <div ref={contentRef} style={{ background: "#070708" }}>
      {/* Reading progress bar */}
      <motion.div
        className="fixed top-0 left-0 right-0 h-[2px] origin-left z-50"
        style={{ scaleX, background: "linear-gradient(90deg, #FFE500, rgba(255,229,0,0.4))" }}
      />

      {/* ── Hero ── */}
      <section className="relative pt-40 pb-16 px-6 overflow-hidden" style={{ borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
        <div className="grain-overlay" />
        {/* Ambient glow */}
        <motion.div
          className="absolute pointer-events-none"
          style={{ width: 500, height: 300, top: 0, left: "10%", background: "radial-gradient(ellipse, rgba(255,229,0,0.04) 0%, transparent 70%)", filter: "blur(60px)" }}
          animate={{ opacity: [0.5, 1, 0.5] }}
          transition={{ duration: 6, repeat: Infinity }}
        />
        <div className="max-w-7xl mx-auto relative">
          <Reveal>
            <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-white/25">Legal</span>
          </Reveal>
          <motion.h1
            className="font-display font-bold text-white leading-[0.9] tracking-tight mt-4 mb-6"
            style={{ fontSize: "clamp(40px, 6vw, 80px)", letterSpacing: "-0.04em" }}
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
          >
            Terms of Service
          </motion.h1>
          <Reveal delay={0.2}>
            <p className="font-mono text-sm text-white/35">
              Last updated: <span className="text-white/50">July 1, 2026</span>
            </p>
          </Reveal>
        </div>
      </section>

      {/* ── Content ── */}
      <section className="px-6 py-16">
        <div className="max-w-7xl mx-auto flex gap-16">
          {/* Sticky TOC */}
          <aside className="hidden lg:block w-56 shrink-0">
            <div className="sticky top-24">
              <p className="font-mono text-[9px] uppercase tracking-[0.22em] text-white/25 mb-5">Contents</p>
              <nav className="space-y-0.5">
                {sections.map(s => {
                  const active = activeSection === s.id;
                  return (
                    <motion.a
                      key={s.id}
                      href={`#${s.id}`}
                      className="flex items-center gap-2 py-1.5 transition-all duration-200 font-mono text-[10px] leading-relaxed"
                      style={{ color: active ? "#FFE500" : "rgba(255,255,255,0.3)", paddingLeft: active ? 6 : 0 }}
                      onClick={e => { e.preventDefault(); document.getElementById(s.id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }}
                      whileHover={{ x: 3 }}
                    >
                      {active && (
                        <motion.div
                          layoutId="terms-toc-dot"
                          className="w-1 h-1 rounded-full shrink-0"
                          style={{ background: "#FFE500" }}
                          transition={{ type: "spring", stiffness: 400, damping: 30 }}
                        />
                      )}
                      {s.title}
                    </motion.a>
                  );
                })}
              </nav>
            </div>
          </aside>

          {/* Body */}
          <div className="flex-1 max-w-3xl space-y-16">
            {sections.map((s, i) => (
              <Reveal key={s.id} delay={i * 0.02}>
                <div id={s.id} style={{ scrollMarginTop: "100px" }}>
                  <motion.div
                    className="h-px mb-6"
                    style={{ background: "rgba(255,255,255,0.06)" }}
                    initial={{ scaleX: 0, originX: 0 }}
                    whileInView={{ scaleX: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                  />
                  <h2 className="font-display font-bold text-white text-xl md:text-2xl mb-5 tracking-tight" style={{ letterSpacing: "-0.02em" }}>
                    {s.title}
                  </h2>
                  <div className="space-y-4">
                    {s.content.split("\n\n").map((para, j) => (
                      <p key={j} className="font-mono text-[12px] leading-[1.9] text-white/45">{para}</p>
                    ))}
                  </div>
                </div>
              </Reveal>
            ))}

            <div className="pt-8" style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}>
              <p className="font-mono text-[11px] text-white/30">
                These terms were last updated on July 1, 2026. For previous versions, contact us at{" "}
                <span className="text-white/50">legal@directioner.app</span>.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
